export const GENERATE_ALERT = 'GENERATE_ALERT';
export const CLEAR_ALERT = 'CLEAR_ALERT';

export const LOGIN_REGISTER_BEGIN = 'LOGIN_REGISTER_BEGIN';
export const LOGIN_REGISTER_SUCCESS = 'LOGIN_REGISTER_SUCCESS';
export const LOGIN_REGISTER_ERROR = 'LOGIN_REGISTER_ERROR';

export const LOGOUT_USER = 'LOGOUT_USER';

export const GET_BEGIN = 'GET_BEGIN';
export const GET_SUCCESS = 'GET_SUCCESS';

export const CHANGE_PAGE = 'CHANGE_PAGE';

export const GET_CURRENT_USER_BEGIN = 'GET_CURRENT_USER_BEGIN';
export const GET_CURRENT_USER_SUCCESS = 'GET_CURRENT_USER_SUCCESS';

export const COMMENT_BEGIN = "CREATE_COMMENT_BEGIN"
export const COMMENT_SUCCESS = "CREATE_COMMENT_SUCCESS"

export const CREATE_COMMENT_BEGIN = "CREATE_COMMENT_BEGIN"
export const CREATE_COMMENT_SUCCESS = "CREATE_COMMENT_SUCCESS"
export const CREATE_COMMENT_ERROR = "CREATE_COMMENT_ERROR"

export const DELETE_COMMENT_BEGIN = "DELETE_COMMENT_BEGIN"
export const DELETE_COMMENT_SUCCESS = "DELETE_COMMENT_SUCCESS"
export const DELETE_COMMENT_ERROR = "DELETE_COMMENT_ERROR"

export const EDIT_COMMENT_BEGIN = "EDIT_COMMENT_BEGIN"
export const EDIT_COMMENT_SUCCESS = "EDIT_COMMENT_SUCCESS"
export const EDIT_COMMENT_ERROR = "EDIT_COMMENT_ERROR"

export const POST_BEGIN = "POST_BEGIN"
export const POST_SUCCESS = "POST_SUCCESS"
export const POST_ERROR = "POST_ERROR"

export const POST_EDIT_START = "POST_EDIT_START"
export const POST_EDIT_SUCCESS = "POST_EDIT_SUCCESS"
export const POST_EDIT_ERROR = "POST_EDIT_ERROR"

export const HANDLE_CHANGE = "HANDLE_CHANGE"

export const SET_IS_EDITING = "SET_IS_EDITING"

export const SET_IS_COMMENT_EDITING = "SET_IS_COMMENT_EDITING"

export const CLEAR_VALUES = "CLEAR_VALUES"